local FightingStyles = {
    "Combat",
    "Dark Step",
    "Electric",
    "Water Kung Fu",
    "Black Leg",
    "Electro",
    "Fishman Karate",
    "Superhuman",
    "Dragon Talon",
    "Death Step",
    "Sharkman Karate",
    "Electric Claw",
    "Godhuman",
    "Sanguine Art",
}

local BloxFruits = {
    "Kilo-Kilo",
    "Rocket-Rocket",
    "Spin-Spin",
    "Smoke-Smoke",
    "Blade-Blade",
    "Spring-Spring",
    "Bomb-Bomb",
    "Spike-Spike",
    "Revive-Revive",
    "Diamond-Diamond",
    "Flame-Flame",
    "Ice-Ice",
    "Sand-Sand",
    "Dark-Dark",
    "Eagle-Eagle",
    "Door-Door",
    "Rubber-Rubber",
    "Ghost-Ghost",
    "Light-Light",
    "Magma-Magma",
    "Quake-Quake",
    "Love-Love",
    "Creation-Creation",
    "Spider-Spider",
    "Sound-Sound",
    "Portal-Portal",
    "Pain-Pain",
    "Lightning-Lightning",
    "Blizzard-Blizzard",
    "Buddha-Buddha",
    "Phoenix-Phoenix",
    "Gravity-Gravity",
    "Shadow-Shadow",
    "Venom-Venom",
    "Soul-Soul",
    "Spirit-Spirit",
    "Control-Control",
    "Dough-Dough",
    "Gas-Gas",
    "Mammoth-Mammoth",
    "T-Rex-T-Rex",
    "Dragon-Dragon",
    "Tiger-Tiger",
    "Yeti-Yeti",
    "Kitsune-Kitsune",
}

local Swords = {
    "Katana",
    "Cutlass",
    "Dual Katana",
    "Iron Mace",
    "Shark Saw",
    "Triple Katana",
    "Twin Hooks",
    "Pipe",
    "Soul Cane",
    "Trident",
    "Longsword",
    "Warden's Sword",
    "Dual-Headed Blade",
    "Flail",
    "Gravity Blade",
    "Dragon Trident",
    "Bisento",
    "Saber",
    "Koko",
    "Jitte",
    "Pole (1st Form)",
    "Pole (2nd Form)",
    "Rengoku",
    "Saddi",
    "Shisui",
    "Wando",
    "Dark Dagger",
    "Buddy Sword",
    "Canvander",
    "Midnight Blade",
    "Oroshi",
    "Saishi",
    "Shizu",
    "Shark Anchor",
    "Spikey Trident",
    "Tushita",
    "Yama",
    "Dragonheart",
    "Fox Lamp",
    "Dark Blade",
    "True Triple Katana",
    "Cursed Dual Katana",
    "Hallow Scythe",
}

local Guns = {
    "Slingshot",
    "Musket",
    "Flintlock",
    "Refined Slingshot",
    "Refined Musket",
    "Refined Flintlock",
    "Dual Flintlock",
    "Cannon",
    "Magma Blaster",
    "Acidum Rifle",
    "Bizarre Rifle",
    "Bazooka",
    "Kabucha",
    "Serpent Bow",
    "Venom Bow",
    "Dragonstorm",
    "Skull Guitar",
    "Soul Guitar",
}

return {
    FightingStyles = FightingStyles,
    BloxFruits     = BloxFruits,
    Swords         = Swords,
    Guns           = Guns,
}