local Config = {

    FarmWeapon          = "Melee",
    SelectedWeaponName  = "",
    FarmAttack          = "Normal",
    AutoFarmLevel       = false,
    AutoFarmNearest     = false,
    FarmIsland          = "",
    FlySpeed            = 300,
    RaidFlySpeed        = 80,   -- velocidade de voo exclusiva da raid (studs/s)
    FlyOffset           = 15,
    HoverHeight         = 10,  -- studs acima do chao que o player fica flutuando durante qualquer funcao ativa
    BringMob            = true,
    BringDistance       = 350,
    BringYOffset        = -10,  -- studs abaixo do player (negativo = abaixo)

    AutoPirateRaid      = false,
    AutoRipIndra        = false,
    AutoTyrantSpawn     = false,
    AutoSoulReaper      = false,
    AutoBigMom          = false,
    AutoFarmBone        = false,
    AutoHakiV2          = false,
    AutoUnlockTemple    = false,
    AutoGodHuman        = false,
    AutoDragonTaylor    = false,
    AutoElectricClaw    = false,
    AutoCakePrince      = false,
    AutoDoughKing       = false,
    AutoGetTushita      = false,
    AutoHolyTorch       = false,
    AutoYama            = false,
    AutoRengoku         = false,
    AutoEliteHunter     = false,
    AutoEliteHunterHop  = false,
    AutoMysticIsland    = false,
    TweenToKitsune      = false,
    AutoAzuerEmber      = false,
    AutoBlazeEmber      = false,
    AutoHydraTree       = false,
    AutoMobDragon       = false,
    DefendVolcano       = false,
    TweenVolcano        = false,
    AutoFindPrehistoric = false,
    AutoCollectBone     = false,
    CollectEgg          = false,
    AutoBartilo         = false,
    ChiefWarden         = false,
    CursedCaptain       = false,
    SailBoat            = false,
    AutoTerrorshark     = false,
    WalkWater           = false,
    AutoKillShark       = false,
    AutoKillPiranha     = false,
    AutoKillFishCrew    = false,
    AutoKillGolem       = false,

    AutoSea3            = false,
    AutoFactory         = false,
    AutoRaid            = false,
    AutoBuyChipRaid     = false,
    AutoStartRaid       = false,
    AutoBuyChipRaidLaw  = false,
    AutoStartRaidLaw    = false,
    AutoRaidLaw         = false,
    AutoDarkBeard       = false,
    AutoSharkmanV2      = false,
    AutoDeathStep       = false,
    AutoBuyEnhancementColour = false,
    AutoBuyLegendarySword    = false,
    AutoGetPole         = false,
    AutoGetSaw          = false,

    AutoSea2            = false,
    AutoBuyTTK          = false,
    AutoGrayBeard       = false,
    AutoDarkBladeV2     = false,

    AutoRaceV3          = false,
    AutoRaceV4          = false,
    AutoQuestRace       = false,
    AutoDooHee          = false,

    AutoStoreFruit      = false,
    TweenFlyFruit       = false,
    GrabFruit           = false,
    AutoFruit           = false,
    AutoFarmFruits      = false,
    NotifyFruitSpawn    = false,
    SelectFruitFarm     = "Farm Level Mastery",
    SelectChipRaid      = "Flame",

    AutoCollectBerry    = false,
    AutoCollectBerryHop = false,
    AutoBarista         = false,
    HakiColor           = "White",
    AutoFarmObsHaki     = false,
    FarmChest           = false,
    FarmChocola         = false,
    AutoSkill           = false,
    AutoSkillZ          = false,
    AutoSkillX          = false,
    AutoSkillC          = false,
    AutoDungeon         = false,
    TweenMGear          = false,
    AutoTryLuck         = false,
    AutoTradeBone       = false,
    AutoPray            = false,

    EnabledPvP          = false,
    KillAura            = false,
    KillAuraRadius      = 1000,
    AimbotGun           = false,
    AimbotSkill         = false,
    AimbotHitBox        = false,
    AimbotMode          = "Nearest Player Aimbot",
    AutoKillPlayer      = false,
    AutoPlayerHunter    = false,
    SelectedPlayer      = "",
    FastAttack          = false,
    FastAttackDelay     = 0.1,

    SelectedBoss        = "None",
    AutoFarmBoss        = false,
    AutoFarmAllBoss     = false,
    AutoFarmRaidBoss    = false,

    SelectedMaterial    = "",
    AutoFarmMaterial    = false,

    MasteryWeapon       = "Gun",
    HealthKillMob       = 30,
    MasteryIsland       = "",
    MasterySkills       = {},
    AutoFarmMastery     = false,

    AutoClick           = true,
    AutoSetSpawn        = false,
    AutoBusoHaki        = true,
    AutoObservation     = false,
    AutoSpeed           = true,
    Speed               = 20,
    AutoSetJump         = true,
    Jump                = 50,
    WalkSpeed           = 16,
    JumpPower           = 50,
    InfiniteJump        = false,
    AntiAFK             = false,
    SafeMode            = false,

    DisableGameNotify   = false,
    NoFog               = true,
    NotifyErroScript    = false,
    NoClip              = false,
    ESPEnabled          = false,
    ESPTeammates        = false,
    ESPIslands          = false,
    ESPFruits           = false,
    ESPChests           = false,
    ESPBerries          = false,
    ESPMirage           = false,
    ESPSeaBeasts        = false,
    ESPNpcs             = false,
    AquaAura            = false,
    RainbowSkills       = false,
    FPSCounter          = false,
    RainbowBillboard    = false,
    SelfHighlight       = false,
    RenderOnFocus       = true,

    UIScale             = 450,
    Language            = "English",

    ScriptStartTime     = os.time(),
    KillCount           = 0,
    StartBring          = false,
    MonFarm             = "",

    ScriptVersion             = "v2.5.7",
    PreLoadVersion       = "v31.3.2",
    FunctionsVersion     = "v2.5.4",
    UIVersion            = "v2.4.9",
    ConfigVersion         = "v2.4.5",
    SaveSettingsVersion    = "v2.4.5",
    QuestsVersion           = "v2.4.5",
    
}
return Config